server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 10
  ratelimiter:
    instances:
      detault:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
  retry:
    instances:
      default:
        maxAttempts: 4
      foo-bar:
        maxAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: user
    password: 123456
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail_on_empty_beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    flyway:
      url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
      user: user
      password: 123456
    sleuth:
      sampler:
        probability: 1.0
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs
