name: Continuos Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v3
     
     - name: Checkout repository
       uses: docker/login-action@v2.0.0
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Setup Java JDK
       uses: actions/setup-java@v3.3.0
       with:
         java-version: '17'
         distribution: 'adopt'
     
     - name: Build Eureka Naming Server Container Image
       working-directory: ./naming-server
       run: mvn spring-boot:build-image -DskipTests
       
     - name: Build Api Gateway Container Image
       working-directory: ./api-gateway
       run: mvn spring-boot:build-image -DskipTests
       
     - name: Build Api Cambio Microservice Container Image
       working-directory: ./cambio-service
       run: mvn spring-boot:build-image -DskipTests
       
     - name: Build Api Book Microseervice Container Image
       working-directory: ./book-service
       run: mvn spring-boot:build-image -DskipTests
       
     - name: Docker Compose Build
       working-directory: .
       run: docker-compose build
